SALESFORCE/force-apps/deploy/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <displayFormat>Attendee-{0000}</displayFormat>
        <label>Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SALESFORCE/force-apps/deploy/main/default/objects/Attendee__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Attendee__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>First Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Attendee__c/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <label>Nickname</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Attendee__c/recordTypes/Attendee.recordType-meta.xml
<RecordType>
    <fullName>Attendee</fullName>
    <active>true</active>
    <description>Delivery attendee</description>
    <label>Attendee</label>
</RecordType>

SALESFORCE/force-apps/deploy/main/default/objects/Attendee__c/recordTypes/Instructor.recordType-meta.xml
<RecordType>
    <fullName>Instructor</fullName>
    <active>true</active>
    <description>Master records for instructors</description>
    <label>Instructor</label>
</RecordType>

force-apps/deploy/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SALESFORCE/force-apps/deploy/main/default/objects/Course_X_Delivery__c/Course_X_Delivery__c.object-meta.xml
<CustomObject>
    <label>Course_X_Delivery</label>
    <nameField>
        <displayFormat>CxD-{0000}</displayFormat>
        <label>Course_X_Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses_X_Delivery</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SALESFORCE/force-apps/deploy/main/default/objects/Course_X_Delivery__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Courses_X_Deliveries</relationshipLabel>
    <relationshipName>Courses_X_Deliveries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Course_X_Delivery__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipLabel>Courses_X_Deliveries</relationshipLabel>
    <relationshipName>Courses_X_Deliveries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Course_X_Delivery__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Order</label>
    <precision>3</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <label>Delivery</label>
    <nameField>
        <label>Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-apps/deploy/main/default/objects/Delivery__c/fields/CurrentExercise__c.field-meta.xml
<CustomField>
    <fullName>CurrentExercise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Exercise</label>
    <referenceTo>Exercise__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-apps/deploy/main/default/objects/Delivery__c/fields/CurrentExerciseIsActive__c.field-meta.xml
<CustomField>
    <fullName>CurrentExerciseIsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current Exercise Is Active</label>
    <type>Checkbox</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Delivery__c/fields/CurrentExerciseStart__c.field-meta.xml
<CustomField>
    <fullName>CurrentExerciseStart__c</fullName>
    <label>Current Exercise Start</label>
    <type>DateTime</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Delivery__c/fields/InstructorLookup__c.field-meta.xml
<CustomField>
    <fullName>InstructorLookup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Instructor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Attendee selected must be an instructor master record</errorMessage>
        <filterItems>
            <field>Attendee__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Instructor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-apps/deploy/main/default/objects/Exercise__c/Exercise__c.object-meta.xml
<CustomObject>
    <label>Exercise</label>
    <nameField>
        <label>Exercise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exercises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SALESFORCE/force-apps/deploy/main/default/objects/Exercise__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Exercises</relationshipLabel>
    <relationshipName>Exercises</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Exercise__c/fields/ExpectedDuration__c.field-meta.xml
<CustomField>
    <fullName>ExpectedDuration__c</fullName>
    <label>Expected Duration</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Exercise__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>3</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Exercise_X_Attendee__c/Exercise_X_Attendee__c.object-meta.xml
<CustomObject>
    <label>Exercise_X_Attendee</label>
    <nameField>
        <displayFormat>ExA-{00}</displayFormat>
        <label>Exercise_X_Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exercises_X_Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SALESFORCE/force-apps/deploy/main/default/objects/Exercise_X_Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Exercises_X_Attendees</relationshipLabel>
    <relationshipName>Exercises_X_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Exercise_X_Attendee__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipLabel>Exercises_X_Attendees</relationshipLabel>
    <relationshipName>Exercises_X_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Exercise_X_Attendee__c/fields/Exercise__c.field-meta.xml
<CustomField>
    <fullName>Exercise__c</fullName>
    <label>Exercise</label>
    <referenceTo>Exercise__c</referenceTo>
    <relationshipLabel>Exercises_X_Attendees</relationshipLabel>
    <relationshipName>Exercises_X_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Exercise_X_Attendee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>00-START</fullName>
            </value>
            <value>
                <fullName>01-WORKING</fullName>
            </value>
            <value>
                <fullName>02-LATER</fullName>
            </value>
            <value>
                <fullName>03-DONE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-apps/deploy/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <displayFormat>Note-{0000}</displayFormat>
        <label>Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SALESFORCE/force-apps/deploy/main/default/objects/Note__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-apps/deploy/main/default/objects/Note__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/classes/TestValidateData.cls
@isTest
public without sharing class TestValidateData {
	@testSetup
	static void makeSingleRecords() {
		Course__c course = new Course__c();
		course.Name = 'Test Course';
		insert course;

		Exercise__c exercise = new Exercise__c();
		exercise.Course__c = course.Id;
		exercise.ExpectedDuration__c = '120 minutes';
		exercise.Name = 'Test Exercise';
		exercise.Order__c = 1;
		insert exercise;

		Attendee__c instructor = new Attendee__c();
		instructor.ChosenDTTM__c = null;
		instructor.Delivery__c = null;
		instructor.Email__c = 'aperez@salesforce.com';
		instructor.FirstName__c = 'Andres';
		instructor.IsInstructor__c = false;
		instructor.LastName__c = 'Perez';
		instructor.Name__c = 'Test Name';
		instructor.Nickname__c = 'ELTOROIT';
		instructor.RecordTypeId = Schema.SObjectType.Attendee__c.getRecordTypeInfosByName().get('Instructor').getRecordTypeId();
		insert instructor;

		Delivery__c delivery = new Delivery__c();
		delivery.CurrentExercise__c = exercise.Id;
		delivery.CurrentExerciseIsActive__c = true;
		delivery.CurrentExerciseStart__c = Datetime.now();
		delivery.InstructorLookup__c = instructor.Id;
		delivery.IsActive__c = true;
		delivery.Name = 'Test Delivery';
		insert delivery;

		Attendee__c student = new Attendee__c();
		student.ChosenDTTM__c = DateTime.now();
		student.Delivery__c = delivery.Id;
		student.Email__c = 'aperez@salesforce.com';
		student.FirstName__c = 'Student';
		student.IsInstructor__c = false;
		student.LastName__c = 'Pizza';
		student.Nickname__c = 'Smarty';
		student.Name__c = 'Test Name';
		instructor.RecordTypeId = Schema.SObjectType.Attendee__c.getRecordTypeInfosByName().get('Attendee').getRecordTypeId();
		insert student;

		Note__c note = new Note__c();
		note.Delivery__c = delivery.Id;
		note.Note__c = 'Sample note';
		insert note;

		Course_X_Delivery__c CxD = new Course_X_Delivery__c();
		CxD.Course__c = course.Id;
		CxD.Delivery__c = delivery.Id;
		CxD.Order__c = 1;
		insert CxD;

		Exercise_X_Attendee__c ExA = new Exercise_X_Attendee__c();
		ExA.Attendee__c = instructor.Id;
		ExA.Delivery__c = 'Test Value 4 De...';
		ExA.Exercise__c = exercise.Id;
		ExA.Status__c = '00-START';
		insert ExA;
	}

	@IsTest
	private static void validateRequiredFields() {
		// Salesforce that if a field is required, it has a value. Here we are checking that the administrator has not made the field not required
		validateRequiredFields('Attendee__c', 'FirstName__c');
		validateRequiredFields('Attendee__c', 'LastName__c');
		validateRequiredFields('Course_X_Delivery__c', 'Order__c');
		validateRequiredFields('Delivery__c', 'InstructorLookup__c');
		validateRequiredFields('Exercise__c', 'Order__c');
		validateRequiredFields('Exercise_X_Attendee__c', 'Status__c');
	}

	@IsTest
	private static void validateAttendeeRequiresDelivery() {
		Attendee__c student = (Attendee__c) clone(getFullRecords('Attendee__c', 'RecordType.Name = \'Attendee\'', 'RecordType.Name')[0]);
		System.assertEquals('Attendee', student.RecordType.Name);

		try {
			student.Delivery__c = null;
			insert student;
			System.assert(false, 'Students do require a delivery');
		} catch (Exception ex) {
			List<String> expectedMessages = new List<String>{ 'Insert failed', 'FIELD_CUSTOM_VALIDATION_EXCEPTION', 'Attendees require a delivery' };
			System.assertEquals('System.DmlException', ex.getTypeName(), 'Expecting: System.DmlException');
			for (String expectedMessage : expectedMessages) {
				System.assert(ex.getMessage().contains(expectedMessage), 'Expecting: ' + expectedMessage);
			}
		}
	}

	@IsTest
	private static void validateInstructorsCanNotHaveDelivery() {
		Attendee__c instructor = (Attendee__c) clone(getFullRecords('Attendee__c', 'RecordType.Name = \'Instructor\'', 'RecordType.Name')[0]);
		System.assertEquals('Instructor', instructor.RecordType.Name);

		Delivery__c delivery = [SELECT Id FROM Delivery__c];

		try {
			instructor.Delivery__c = delivery.Id;
			insert instructor;
			System.assert(false, 'Instructors can not have deliveries');
		} catch (Exception ex) {
			List<String> expectedMessages = new List<String>{
				'Insert failed',
				'FIELD_CUSTOM_VALIDATION_EXCEPTION',
				'Instructors can\'t have delivery'
			};
			System.assertEquals('System.DmlException', ex.getTypeName(), 'Expecting: System.DmlException');
			for (String expectedMessage : expectedMessages) {
				System.assert(ex.getMessage().contains(expectedMessage), 'Expecting: ' + expectedMessage);
			}
		}
	}

	private static void validateRequiredFields(String SObjectName, String FieldName) {
		SObject record = getFullRecords(SObjectName)[0];
		SObject newRecord = clone(record);
		newRecord.put(FieldName, null);
		try {
			insert newRecord;
			System.assert(false);
		} catch (Exception ex) {
			List<String> expectedMessages = new List<String>{ 'Insert failed', 'REQUIRED_FIELD_MISSING', fieldName };
			System.assertEquals('System.DmlException', ex.getTypeName(), 'Expecting: System.DmlException');
			for (String expectedMessage : expectedMessages) {
				System.assert(ex.getMessage().contains(expectedMessage), 'Expecting: ' + expectedMessage);
			}
		}
	}

	private static List<sObject> getFullRecords(String SObjectName) {
		return getFullRecords(SObjectName, null, null);
	}
	private static List<sObject> getFullRecords(String SObjectName, String filter) {
		return getFullRecords(SObjectName, filter, null);
	}
	private static List<sObject> getFullRecords(String SObjectName, String filter, String extraFields) {
		String SOQL = '';
		for (String field : Schema.getGlobalDescribe().get(SObjectName).getDescribe().fields.getMap().keySet()) {
			if (SOQL != '')
				SOQL += ', ';
			SOQL += field;
		}
		if (extraFields != null) {
			SOQL += ', ' + extraFields;
		}
		SOQL = 'SELECT ' + SOQL + ' FROM ' + SObjectName;
		if (filter != null) {
			SOQL += ' WHERE ' + filter;
		}
		return Database.query(SOQL);
	}

	private static sObject clone(Sobject original) {
		Boolean preserveId = false;
		Boolean isDeepClone = true;
		Sobject newRecord = original.clone(preserveId, isDeepClone);
		return newRecord;
	}
}