SALESFORCE/force-apps/deploy/main/default/objects/Course_X_Delivery__c/Course_X_Delivery__c.object-meta.xml
<CustomObject>
    <label>Course_X_Delivery</label>
    <nameField>
        <displayFormat>CxD-{0000}</displayFormat>
        <label>Course_X_Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses_X_Delivery</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-apps/deploy/main/default/objects/Course_X_Delivery__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipLabel>Courses_X_Deliveries</relationshipLabel>
    <relationshipName>Courses_X_Deliveries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <label>Delivery</label>
    <nameField>
        <label>Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-apps/deploy/main/default/objects/Delivery__c/fields/CurrentExercise__c.field-meta.xml
<CustomField>
    <fullName>CurrentExercise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Exercise</label>
    <referenceTo>Exercise__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-apps/deploy/main/default/objects/Delivery__c/fields/CurrentExerciseIsActive__c.field-meta.xml
<CustomField>
    <fullName>CurrentExerciseIsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current Exercise Is Active</label>
    <type>Checkbox</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Delivery__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <label>Instructor</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andres Perez</fullName>
                <default>true</default>
                <label>Andres Perez</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-apps/deploy/main/default/objects/Exercise__c/Exercise__c.object-meta.xml
<CustomObject>
    <label>Exercise</label>
    <nameField>
        <label>Exercise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exercises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SALESFORCE/force-apps/deploy/main/default/objects/Exercise_X_Student__c/Exercise_X_Student__c.object-meta.xml
<CustomObject>
    <label>Exercise_X_Student</label>
    <nameField>
        <displayFormat>ExS-{00}</displayFormat>
        <label>Exercise_X_Student Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exercises_X_Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-apps/deploy/main/default/objects/Exercise_X_Student__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Exercise_X_Student__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Exercises_X_Students</relationshipLabel>
    <relationshipName>Exercises_X_Students</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Instructor__c/Instructor__c.object-meta.xml
<CustomObject>
    <label>Instructor</label>
    <nameField>
        <label>Instructor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instructors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SALESFORCE/force-apps/deploy/main/default/objects/Student__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-apps/deploy/main/default/objects/Student__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <externalId>true</externalId>
    <label>Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-apps/deploy/main/default/classes/Student.cls
public without sharing class Student {
	@AuraEnabled(cacheable=true)
	public static List<Delivery__c> getActiveDeliveries() {
		return [
			SELECT Id, Name, CurrentExercise__r.Name, Instructor__c
			FROM Delivery__c
			WHERE Id IN (SELECT Delivery__c FROM Course_X_Delivery__c) AND IsActive__c = TRUE
			ORDER BY Name ASC
		];
	}

	@AuraEnabled(cacheable=true)
	public static List<Student__c> getStudentsForDelivery(String deliveryId) {
		return [SELECT Id, Name FROM Student__c WHERE Delivery__c = :deliveryId ORDER BY Name ASC];
	}

	@AuraEnabled(cacheable=true)
	public static Student__c getStudentById(String studentId) {
		return [SELECT Id, Name FROM Student__c WHERE Id = :studentId];
	}

	@AuraEnabled(cacheable=true)
	public static Delivery__c getDeliveryById(String deliveryId) {
		return [
			SELECT Id, Name, Instructor__c, CurrentExercise__c, CurrentExerciseIsActive__c
			FROM Delivery__c
			WHERE Id = :deliveryId
		];
	}

	@AuraEnabled(cacheable=true)
	public static Exercise__c getExercisetById(String exerciseId) {
		return [SELECT Id, Name FROM Exercise__c WHERE Id = :exerciseId];
	}

	@AuraEnabled(cacheable=true)
	public static Exercise__c getActiveExercise(String deliveryId) {
		Exercise__c output = null;
		List<Exercise__c> exercises = [
			SELECT Id, Name
			FROM Exercise__c
			WHERE
				Id IN (
					SELECT CurrentExercise__c
					FROM Delivery__c
					WHERE Id = :deliveryId AND CurrentExerciseIsActive__c = TRUE
				)
		];
		if (exercises.size() == 1) {
			output = exercises[0];
		}
		return output;
	}

	@AuraEnabled
	public static Student__c registerStudent(String deliveryId, String studentName) {
		Student__c student = new Student__c(
			Name = studentName,
			delivery__c = deliveryId,
			Key__c = deliveryId + '|' + studentName
		);
		upsert student Key__c;
		return student;
	}

	@AuraEnabled(cacheable=true)
	public static Map<String, Object> validateRegistration(String deliveryId, String studentId) {
		List<String> errors = new List<String>();
		Map<String, String> output = new Map<String, String>();
		output.put('delivery', '');
		output.put('student', '');

		List<Delivery__c> deliveries = [SELECT Id, Name FROM Delivery__c WHERE Id = :deliveryId AND IsActive__c = TRUE];
		if (deliveries.size() == 1) {
			output.put('delivery', deliveries[0]);
		} else {
			errors.add('Invalid deliveryId');
		}

		List<Student__c> students = [SELECT Id, Name FROM Student__c WHERE Id = :studentId AND Delivery__c = :deliveryId];
		if (students.size() == 1) {
			output.put('studen', students[0]);
		} else {
			errors.add('Invalid studentId');
		}

		if (errors.size() > 0) {
			throw new CalloutException('Registration data is not valid: ' + JSON.serialize(errors));
		}

		return output;
	}

	@AuraEnabled
	public static void updateStatus(String exerciseId, String studentId, String status) {
		List<Exercise_X_Student__c> ExSs = [
			SELECT Id, Name, Exercise__c, Student__c, Status__c
			FROM Exercise_X_Student__c
			WHERE Student__c = :studentId AND Exercise__c = :exerciseId
		];
		Exercise_X_Student__c ExS;
		if (ExSs.size() == 0) {
			ExS = new Exercise_X_Student__c(Exercise__c = exerciseId, Student__c = studentId);
		} else if (ExSs.size() == 1) {
			ExS = ExSs[0];
		} else {
			throw new AuraException('Multiple records per student');
		}
		ExS.Status__c = status;
		upsert ExS;
	}
}