SALESFORCE/force-apps/deploy/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <label>Delivery</label>
    <nameField>
        <label>Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SALESFORCE/force-apps/deploy/main/default/objects/NotifySocket__e/NotifySocket__e.object-meta.xml
<CustomObject>
    <label>NotifySocket</label>
    <pluralLabel>NotifySocket</pluralLabel>
</CustomObject>

SALESFORCE/force-apps/deploy/main/default/objects/NotifySocket__e/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <label>Delivery</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/NotifySocket__e/fields/EntityName__c.field-meta.xml
<CustomField>
    <fullName>EntityName__c</fullName>
    <label>Entity Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/NotifySocket__e/fields/Records__c.field-meta.xml
<CustomField>
    <fullName>Records__c</fullName>
    <label>Records</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/classes/StudentNotifier.cls
public with sharing class StudentNotifier {
	public static void publishEvents(String entityName) {
		Map<Id, Integer> deliveryIds = new Map<Id, Integer>();
		List<SObject> sobjs = Trigger.isDelete ? Trigger.old : Trigger.new;

		for (Sobject sobj : sobjs) {
			String key = (String) sobj.get('Delivery__c');
			if (deliveryIds.containsKey(key)) {
				deliveryIds.put(key, deliveryIds.get(key) + 1);
			} else {
				deliveryIds.put(key, 1);
			}
		}

		List<NotifySocket__e> socketEvents = new List<NotifySocket__e>();
		for (Id key : deliveryIds.keySet()) {
			Integer count = deliveryIds.get(key);
			socketEvents.add(new NotifySocket__e(Delivery__c = key, EntityName__c = entityName, Records__c = count));
		}
		List<Database.SaveResult> results = EventBus.publish(socketEvents);
		for (Database.SaveResult sr : results) {
			if (!sr.isSuccess()) {
				String messages = 'Error returned: ';
				for (Database.Error err : sr.getErrors()) {
					messages += err.getStatusCode() + ' - ' + err.getMessage() + ' | ';
				}
				throw new CalloutException(messages);
			}
		}
	}
}