force-apps/deploy/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SALESFORCE/force-apps/deploy/main/default/objects/Course_X_Delivery__c/Course_X_Delivery__c.object-meta.xml
<CustomObject>
    <label>Course_X_Delivery</label>
    <nameField>
        <displayFormat>CxD-{0000}</displayFormat>
        <label>Course_X_Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses_X_Delivery</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SALESFORCE/force-apps/deploy/main/default/objects/Course_X_Delivery__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Courses_X_Deliveries</relationshipLabel>
    <relationshipName>Courses_X_Deliveries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-apps/deploy/main/default/objects/Course_X_Delivery__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipLabel>Courses_X_Deliveries</relationshipLabel>
    <relationshipName>Courses_X_Deliveries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Course_X_Delivery__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Order</label>
    <precision>3</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <label>Delivery</label>
    <nameField>
        <label>Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-apps/deploy/main/default/objects/Delivery__c/fields/ActivatedDTTM__c.field-meta.xml
<CustomField>
    <fullName>ActivatedDTTM__c</fullName>
    <label>Activated DTTM</label>
    <type>DateTime</type>
</CustomField>

force-apps/deploy/main/default/objects/Delivery__c/fields/ActiveExercise__c.field-meta.xml
<CustomField>
    <fullName>ActiveExercise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Exercise</label>
    <referenceTo>Exercise__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-apps/deploy/main/default/objects/Exercise__c/Exercise__c.object-meta.xml
<CustomObject>
    <label>Exercise</label>
    <nameField>
        <label>Exercise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exercises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SALESFORCE/force-apps/deploy/main/default/objects/Exercise__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Exercises</relationshipLabel>
    <relationshipName>Exercises</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Exercise__c/fields/ExpectedDuration__c.field-meta.xml
<CustomField>
    <fullName>ExpectedDuration__c</fullName>
    <label>Expected Duration</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-apps/deploy/main/default/objects/Exercise__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Exercise_X_Student__c/Exercise_X_Student__c.object-meta.xml
<CustomObject>
    <label>Exercise_X_Student</label>
    <nameField>
        <displayFormat>ExS-{00}</displayFormat>
        <label>Exercise_X_Student Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exercises_X_Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-apps/deploy/main/default/objects/Exercise_X_Student__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Exercise_X_Student__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Exercises_X_Students</relationshipLabel>
    <relationshipName>Exercises_X_Students</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-apps/deploy/main/default/objects/Exercise_X_Studnet__c/fields/Exercise__c.field-meta.xml
<CustomField>
    <fullName>Exercise__c</fullName>
    <label>Exercise</label>
    <referenceTo>Exercise__c</referenceTo>
    <relationshipLabel>Exercises_X_Students</relationshipLabel>
    <relationshipName>Exercises_X_Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Student__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-apps/deploy/main/default/classes/Instructor.cls
public without sharing class Instructor {
    @AuraEnabled(cacheable=true)
	public static List<Course_X_Delivery__c> getActiveCxDs() {
		return [
			SELECT Id, Name, Course__r.Name, Delivery__r.Name, Delivery__r.ActiveExercise__r.Name
			FROM Course_X_Delivery__c
			WHERE Delivery__r.IsActive__c = TRUE
			ORDER BY Delivery__r.Name ASC, Order__c ASC
		];
	}

	@AuraEnabled(cacheable=true)
	public static List<Exercise__c> getAllExercisesForCxD(String CxD) {
		List<Exercise__c> output = new List<Exercise__c>();

		if (CxD != '') {
			List<String> parts = CxD.split('\\|');
			String courseId = parts[0];
			String deliveryId = parts[1];

			output = [
				SELECT Id, Name, Course__c, Course__r.Name, ExpectedDuration__c, Order__c
				FROM Exercise__c
				WHERE Course__c = :courseId
				ORDER BY Order__c ASC
			];
		}

		return output;
	}

	@AuraEnabled(cacheable=true)
	public static Map<String, Object> getStudentsProgress(String CxD, String exerciseId) {
		Map<String, Object> output = new Map<String, Object>();

		if (CxD != '') {
			List<String> parts = CxD.split('\\|');
			String courseId = parts[0];
			String deliveryId = parts[1];

			output.put(
				'TABLE',
				[
					SELECT
						Id,
						Name,
						(SELECT ID, Status__c, lastModifiedDate FROM Exercises_X_Students__r WHERE Exercise__c = :exerciseId)
					FROM Student__c
					WHERE Delivery__c = :deliveryId
					ORDER BY Name ASC
				]
			);
			output.put('EXERCISES', Instructor.getAllExercisesForCxD(CxD));
			output.put(
				'DELIVERY',
				[
					SELECT ActiveExercise__r.Name, ActivatedDTTM__c
					FROM Delivery__c
					WHERE Id = :deliveryId AND ActiveExercise__c != NULL
				]
			);
			// output.put('DTTM', Datetime.now());
		}

		return output;
	}

	@AuraEnabled
	public static Delivery__c startStopExercise(String CxD, String exerciseId, Boolean isStart) {
		Delivery__c output = null;

		if (CxD != '') {
			List<String> parts = CxD.split('\\|');
			String courseId = parts[0];
			String deliveryId = parts[1];

			try {
				if (isStart) {
					update new Delivery__c(
						Id = deliveryId,
						ActiveExercise__c = exerciseId,
						ActivatedDTTM__c = Datetime.now()
					);
				} else {
					update new Delivery__c(Id = deliveryId, ActiveExercise__c = null, ActivatedDTTM__c = null);
				}
				output = [SELECT ActiveExercise__r.Name, ActivatedDTTM__c FROM Delivery__c WHERE Id = :deliveryId];
			} catch (Exception e) {
				throw new AuraHandledException(e.getMessage());
			}
		}

		return output;
	}
}