force-apps/deploy/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SALESFORCE/force-apps/deploy/main/default/objects/Course_X_Delivery__c/Course_X_Delivery__c.object-meta.xml
<CustomObject>
    <label>Course_X_Delivery</label>
    <nameField>
        <displayFormat>CxD-{0000}</displayFormat>
        <label>Course_X_Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses_X_Delivery</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SALESFORCE/force-apps/deploy/main/default/objects/Course_X_Delivery__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Courses_X_Deliveries</relationshipLabel>
    <relationshipName>Courses_X_Deliveries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Course_X_Delivery__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipLabel>Courses_X_Deliveries</relationshipLabel>
    <relationshipName>Courses_X_Deliveries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Course_X_Delivery__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Order</label>
    <precision>3</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <label>Delivery</label>
    <nameField>
        <label>Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-apps/deploy/main/default/objects/Delivery__c/fields/CurrentExercise__c.field-meta.xml
<CustomField>
    <fullName>CurrentExercise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Exercise</label>
    <referenceTo>Exercise__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-apps/deploy/main/default/objects/Delivery__c/fields/CurrentExerciseIsActive__c.field-meta.xml
<CustomField>
    <fullName>CurrentExerciseIsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current Exercise Is Active</label>
    <type>Checkbox</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Delivery__c/fields/CurrentExerciseStart__c.field-meta.xml
<CustomField>
    <fullName>CurrentExerciseStart__c</fullName>
    <label>Current Exercise Start</label>
    <type>DateTime</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Delivery__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <label>Instructor</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andres Perez</fullName>
                <default>true</default>
                <label>Andres Perez</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-apps/deploy/main/default/objects/Exercise__c/Exercise__c.object-meta.xml
<CustomObject>
    <label>Exercise</label>
    <nameField>
        <label>Exercise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exercises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SALESFORCE/force-apps/deploy/main/default/objects/Exercise__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Exercises</relationshipLabel>
    <relationshipName>Exercises</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Exercise__c/fields/ExpectedDuration__c.field-meta.xml
<CustomField>
    <fullName>ExpectedDuration__c</fullName>
    <label>Expected Duration</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Exercise__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>3</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Exercise_X_Student__c/Exercise_X_Student__c.object-meta.xml
<CustomObject>
    <label>Exercise_X_Student</label>
    <nameField>
        <displayFormat>ExS-{00}</displayFormat>
        <label>Exercise_X_Student Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exercises_X_Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-apps/deploy/main/default/objects/Exercise_X_Student__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Exercise_X_Student__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Exercises_X_Students</relationshipLabel>
    <relationshipName>Exercises_X_Students</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Instructor__c/Instructor__c.object-meta.xml
<CustomObject>
    <label>Instructor</label>
    <nameField>
        <label>Instructor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instructors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SALESFORCE/force-apps/deploy/main/default/objects/Instructor__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Last Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-apps/deploy/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <displayFormat>Note-{0000}</displayFormat>
        <label>Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SALESFORCE/force-apps/deploy/main/default/objects/Note__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-apps/deploy/main/default/objects/Note__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Student__c/fields/ChosenDTTM__c.field-meta.xml
<CustomField>
    <fullName>ChosenDTTM__c</fullName>
    <label>Chosen DTTM</label>
    <type>DateTime</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/objects/Student__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-apps/deploy/main/default/objects/Student__c/fields/IsInstructor__c.field-meta.xml
<CustomField>
    <fullName>IsInstructor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Instructor</label>
    <type>Checkbox</type>
</CustomField>

SALESFORCE/force-apps/deploy/main/default/classes/StudentNotifier_Test.cls
@IsTest
public with sharing class StudentNotifier_Test {
	@IsTest
	private static void TestSimpleRecordCreation() {
		Course__c course = new Course__c();
		course.Name = 'Test Course';
		insert course;

		Exercise__c exercise = new Exercise__c();
		exercise.Course__c = course.Id;
		exercise.Name = 'Test Exercise';
		exercise.ExpectedDuration__c = '120 minutes';
		exercise.Order__c = 1;
		insert exercise;

		Delivery__c delivery = new Delivery__c();
		delivery.CurrentExercise__c = exercise.Id;
		delivery.CurrentExerciseIsActive__c = true;
		delivery.CurrentExerciseStart__c = Datetime.now();
		delivery.Name = 'Test Delivery';
		delivery.Instructor__c = 'Andres Perez';
		delivery.IsActive__c = true;
		insert delivery;

		Note__c note = new Note__c();
		note.Delivery__c = delivery.Id;
		note.Note__c = 'Sample note';
		insert note;

		Student__c student = new Student__c();
		student.ChosenDTTM__c = DateTime.now();
		student.Delivery__c = delivery.Id;
		student.Email__c = 'aperez@salesforce.com';
		student.FirstName__c = 'Andres';
		student.IsInstructor__c = true;
		student.LastName__c = 'Perez';
		student.Nickname__c = 'ELTOROIT';
		student.Name = 'Test Name';
		insert student;

		Course_X_Delivery__c CxD = new Course_X_Delivery__c();
		CxD.Course__c = course.Id;
		CxD.Delivery__c = delivery.Id;
		CxD.Order__c = 1;
		insert CxD;

		Exercise_X_Student__c ExS = new Exercise_X_Student__c();
		ExS.Delivery__c = 'Test Value For Delivery Id';
		ExS.Exercise__c = exercise.Id;
		ExS.Status__c = '00-START';
		ExS.Student__c = student.Id;
		insert ExS;
	}
}